// Code generated by protoc-gen-goconsgen. DO NOT EDIT.
// source: proto/gosearch/contracts/models.proto

package contracts

func NewStringArray(
	values []string,
) *StringArray {
	return &StringArray{
		Values: values,
	}
}

func NewEmptyResponse() *EmptyResponse {
	return &EmptyResponse{}
}

func NewCreateIndexedDocumentCommand() *CreateIndexedDocumentCommand {
	return &CreateIndexedDocumentCommand{}
}

func NewSearchQuery(
	query string,
) *SearchQuery {
	return &SearchQuery{
		Query: query,
	}
}

func NewDocumentCreatedResponse() *DocumentCreatedResponse {
	return &DocumentCreatedResponse{}
}

func NewSearchResponse() *SearchResponse {
	return &SearchResponse{}
}
