// [START declaration]

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: proto/gosearch/contracts/service.proto

package contracts

import (
	context "context"
	contracts "github.com/BetaLixT/gosearch/pkg/domain/contracts"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Documents_Create_FullMethodName = "/gosearch.Documents/Create"
	Documents_Query_FullMethodName  = "/gosearch.Documents/Query"
)

// DocumentsClient is the client API for Documents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentsClient interface {
	// Query for existing tasks
	Create(ctx context.Context, in *contracts.CreateIndexedDocumentCommand, opts ...grpc.CallOption) (*contracts.DocumentCreatedResponse, error)
	Query(ctx context.Context, in *contracts.SearchQuery, opts ...grpc.CallOption) (*contracts.SearchResponse, error)
}

type documentsClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentsClient(cc grpc.ClientConnInterface) DocumentsClient {
	return &documentsClient{cc}
}

func (c *documentsClient) Create(ctx context.Context, in *contracts.CreateIndexedDocumentCommand, opts ...grpc.CallOption) (*contracts.DocumentCreatedResponse, error) {
	out := new(contracts.DocumentCreatedResponse)
	err := c.cc.Invoke(ctx, Documents_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) Query(ctx context.Context, in *contracts.SearchQuery, opts ...grpc.CallOption) (*contracts.SearchResponse, error) {
	out := new(contracts.SearchResponse)
	err := c.cc.Invoke(ctx, Documents_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentsServer is the server API for Documents service.
// All implementations must embed UnimplementedDocumentsServer
// for forward compatibility
type DocumentsServer interface {
	// Query for existing tasks
	Create(context.Context, *contracts.CreateIndexedDocumentCommand) (*contracts.DocumentCreatedResponse, error)
	Query(context.Context, *contracts.SearchQuery) (*contracts.SearchResponse, error)
	mustEmbedUnimplementedDocumentsServer()
}

// UnimplementedDocumentsServer must be embedded to have forward compatible implementations.
type UnimplementedDocumentsServer struct {
}

func (UnimplementedDocumentsServer) Create(context.Context, *contracts.CreateIndexedDocumentCommand) (*contracts.DocumentCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDocumentsServer) Query(context.Context, *contracts.SearchQuery) (*contracts.SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDocumentsServer) mustEmbedUnimplementedDocumentsServer() {}

// UnsafeDocumentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentsServer will
// result in compilation errors.
type UnsafeDocumentsServer interface {
	mustEmbedUnimplementedDocumentsServer()
}

func RegisterDocumentsServer(s grpc.ServiceRegistrar, srv DocumentsServer) {
	s.RegisterService(&Documents_ServiceDesc, srv)
}

func _Documents_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.CreateIndexedDocumentCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documents_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Create(ctx, req.(*contracts.CreateIndexedDocumentCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(contracts.SearchQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Documents_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).Query(ctx, req.(*contracts.SearchQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Documents_ServiceDesc is the grpc.ServiceDesc for Documents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Documents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gosearch.Documents",
	HandlerType: (*DocumentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Documents_Create_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Documents_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/gosearch/contracts/service.proto",
}
