trigger:
  - publish/test

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "60cd34e1-b31f-4bf6-a896-6545aed1bcdb"
  containerRegistry: "udccoreacr.azurecr.io"
  vmImage: "ubuntu-latest"
  tag: test

stages:
  - stage: Build
    displayName: "Build and push stage"
    jobs:
      - job: Build
        displayName: "Build and push"
        pool:
          vmImage: $(vmImage)
        steps:
          - task: Docker@2
            inputs:
              command: "login"
              addPipelineData: false
              addBaseImageData: false
              containerRegistry: $(dockerRegistryServiceConnection)

          - checkout: self
            persistCredentials: true

          - task: CmdLine@2
            displayName: "Build and push"
            inputs:
              workingDirectory: $(Build.SourcesDirectory)
              script: |
                echo Running build and push
                make ci tu-pat=$(System.AccessToken) registry=$(containerRegistry) env=$(tag)

                echo creating tags
                git tag -d $(tag) || true
                git tag $(tag)
                git push origin :$(tag) || true
                git push origin $(tag)

  - stage: PullRequest
    displayName: Create Pull Request
    jobs:
      - job: PullRequest
        displayName: PullRequest
        pool:
          vmImage: "windows-latest"
        steps:
          - task: CreatePullRequest@1
            inputs:
              repoType: "Azure DevOps"
              repositorySelector: "currentBuild"
              sourceBranch: "$(Build.SourceBranch)"
              targetBranch: "publish/uat"
              title: "UAT sync up"
              reviewers: "alphin@cxunicorn.com;tamas@cxunicorn.com;karimh@cxunicorn.com"
